package com.jakemarsden.java.lexer.token;

public enum Operator {

  // assignment
  ASSIGNMENT,

  // numerical
  ADDITION,
  DIVISION,
  MULTIPLICATION,
  REMAINDER,
  SUBTRACTION,

  // numerical assignment
  ADDITION_ASSIGNMENT,
  DECREMENT,
  DIVISION_ASSIGNMENT,
  INCREMENT,
  MULTIPLICATION_ASSIGNMENT,
  REMAINDER_ASSIGNMENT,
  SUBTRACTION_ASSIGNMENT,

  // integral
  BITWISE_AND,
  BITWISE_COMPLEMENT,
  BITWISE_IOR,
  BITWISE_XOR,
  LEFT_SHIFT,
  RIGHT_SHIFT,
  UNSIGNED_RIGHT_SHIFT,

  // integral assignment
  BITWISE_AND_ASSIGNMENT,
  BITWISE_IOR_ASSIGNMENT,
  BITWISE_XOR_ASSIGNMENT,
  LEFT_SHIFT_ASSIGNMENT,
  RIGHT_SHIFT_ASSIGNMENT,
  UNSIGNED_RIGHT_SHIFT_ASSIGNMENT,

  // comparison
  EQUAL_TO,
  LOGICAL_AND,
  LOGICAL_COMPLEMENT,
  LOGICAL_IOR,
  NOT_EQUAL_TO,
  TERNARY1,
  TERNARY2,

  // numerical comparison
  GREATER_THAN,
  GREATER_THAN_OR_EQUAL_TO,
  LESS_THAN,
  LESS_THAN_OR_EQUAL_TO,

  // lambda
  LAMBDA
}
